"""Constants used by the control-module. Keeps usage simple"""

A = "A_BUTTON"
B = "B_BUTTON"
X = "X_BUTTON"
Y = "Y_BUTTON"


UP    = "DPAD_UP"
DOWN  = "DPAD_DOWN"
LEFT  = "DPAD_LEFT"
RIGHT = "DPAD_RIGHT"


RB = "RB"
LB = "LB"
RT = "RT"
LT = "LT"


MSL = "MINISTICK_LEFT"
MSR = "MINISTICK_RIGHT"

MSLP = "MINISTICK_LEFT_PRESSED"
MSRP = "MINISTICK_RIGHT_PRESSED"


BACK  = "BACK"
START = "START"
GUIDE = "GUIDE"


BATTERY_TYPE              = "BATTERY_TYPE"
BATTERY_TYPE_DISCONNECTED = "BATTERY_DISCONNECTED"
BATTERY_TYPE_WIRED        = "BATTERY_WIRED"
BATTERY_TYPE_ALKALINE     = "BATTERY_ALKALINE"
BATTERY_TYPE_NIMH         = "BATTERY_NIMH"
BATTERY_TYPE_UNKNOWN      = "BATTERY_UNKNOWN"

BATTERY_LEVEL = "BATTERY_LEVEL"
BATTERY_LEVEL_EMPTY  = "BATTERY_EMPTY"
BATTERY_LEVEL_LOW    = "BATTERY_LOW"
BATTERY_LEVEL_MEDIUM = "BATTERY_MEDIUM"
BATTERY_LEVEL_FULL   = "BATTERY_FULL"
